name: 'jandi-notify'

inputs:
  status:
    required: false
    description: CI/CD status
    default: 'failure'
  jandi_incoming_url:
    description: jandi webhook URL
    required: true

description: jandi notify action
runs:
  using: 'composite'
  steps:
    - name: Send jandi
      shell: bash
      run: |
        RAW_COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
        COMMIT_MESSAGE="${RAW_COMMIT_MESSAGE@Q}"        
        curl \
        -X POST "${{ inputs.jandi_incoming_url }}" \
        -H "Accept: application/vnd.tosslab.jandi-v2+json" \
        -H "Content-Type: application/json" \
        --data-ascii '{"body":"📢 EVUI CI/CD Notification - ⛔ Deployment failed", "connectColor":"#FF4C15", "connectInfo":[{"title":"Commit message","description":"- '"${COMMIT_MESSAGE}"'"}]}'
