name: 'jandi-notify'

inputs:
  status:
    required: false
    default: 'failure'
  jandi_incoming_url:
    required: true

runs:
  using: 'composite'
  steps:
    - name: Send jandi
      shell: bash
      run: |
        if [ "${{ inputs.status }}" = "success" ]; then
          EMOTICON="✅"
        else
          EMOTICON="❌"
        fi

        curl \
        -X POST "${{ inputs.jandi_incoming_url }}" \
        -H "Accept: application/vnd.tosslab.jandi-v2+json" \
        -H "Content-Type: application/json" \
        --data-binary '{"body":"✅ Deployment succeeded", "connectColor":"#3C81F6", "connectInfo":[{"title":"Github pages","description":"[[EVUI]](https://ex-em.github.io/EVUI)",{"title":"Commit messages","description":'"${{ github.event.head_commit.message }}"'}'
