name: 'jandi-notify'

inputs:
  status:
    required: false
    default: 'failure'
  jandi_incoming_url:
    required: true

runs:
  using: 'composite'
  steps:
    - name: Send jandi
      shell: bash
      run: |
        if [ "${{ inputs.status }}" = "success" ]; then
          EMOTICON="✅"
        else
          EMOTICON="❌"
        fi
        
        MSG="{ \"text\":\">${EMOTICON} workflow (<https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}|${GITHUB_WORKFLOW}>) in <https://github.com/${GITHUB_REPOSITORY}|${GITHUB_REPOSITORY}>\n><https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}/checks|${GITHUB_JOB}> job ${{ inputs.status }}, branch=\`${GITHUB_REF#refs/heads/}\`\"}"
        echo $MSG
        echo "$MSG"
        echo "${MSG}"
        curl -X POST -H "Accept: application/vnd.tosslab.jandi-v2+json" -H "Content-Type: application/json" --data-binary '{"body": "$MSG"}' "${{ inputs.jandi_incoming_url }}"
