name: 'jandi-notify'

inputs:
  status:
    required: false
    default: 'failure'
  jandi_incoming_url:
    required: true

runs:
  using: 'composite'
  steps:
    - name: Send jandi
      shell: bash
      run: |
        COMMIT_MESSAGE="${{ github.event.head_commit.message }}"

        if [ "${{ inputs.status }}" = "success" ]; then          
          curl \
          -X POST "${{ inputs.jandi_incoming_url }}" \
          -H "Accept: application/vnd.tosslab.jandi-v2+json" \
          -H "Content-Type: application/json" \
          --data-binary '{"body":"📢 EVUI CI/CD Notipication - ✅ Deployment succeeded", "connectColor":"#4285F6", "connectInfo":[{"title":"Commit Message","description":"- '"${COMMIT_MESSAGE}"'"},{"title":"EVUI Document","description":"- [[EVUI]](https://ex-em.github.io/EVUI)"}]}'
        else
          curl \
          -X POST "${{ inputs.jandi_incoming_url }}" \
          -H "Accept: application/vnd.tosslab.jandi-v2+json" \
          -H "Content-Type: application/json" \
          --data-binary '{"body":"📢 EVUI CI/CD Notipication - ⛔ Deployment failed", "connectColor":"#FF4C15", "connectInfo":[{"title":"Commit Message","description":"- '"${COMMIT_MESSAGE}"'"},{"title":"Error Log","description":"- [[Workflow]](https://github.com/'"${GITHUB_REPOSITORY}"'/actions/runs/'"${GITHUB_RUN_ID}"'|'"${GITHUB_WORKFLOW}"')"}]}'
        fi
